syntax = "proto3";

package author;

import "protos/entities.proto";

message RetrieveAuthorRequest {
    uint32 id = 1;
}

message CreateAuthorRequest {
    string name = 1;
    uint32 age = 2;
    bool alive = 3;
}

message SingleAuthorResponse {
    uint32 id = 1;
    string name = 2;
    uint32 age = 3;
    bool alive = 4;
}

message AuthorWithBooksResponse {
    uint32 id = 1;
    string name = 2;
    uint32 age = 3;
    bool alive = 4;
    repeated entities.Book books = 5;
}

service AuthorService {
    rpc RetrieveAuthor(RetrieveAuthorRequest) returns (AuthorWithBooksResponse);
    rpc CreateAuthor(CreateAuthorRequest) returns (SingleAuthorResponse);
}
